name: okay
description: Typesafe error-handling for dart . An implementation of rust's `Result` type in dart.
version: 1.1.0
homepage: https://hextools.0xba1.xyz
repository: https://github.com/0xba1/okay.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  http: ^0.13.4
  test: ^1.21.2
  very_good_analysis: ^3.0.1
